### PR TITLE
Feature add migrations

### PR DESCRIPTION
**Pull request by DominikSerwatka**
- add flyway plugin to make migrations
- No console application at the moment
- To run migration: mvn flyway:migrate

### CODE REVIEW

**Comment by DominikSerwatka** [comment]
- Add "migrate" to Makefile in order to run migration 
- Application run as Console App
- Add simple example migration to resources/db/migration

**Comment by jdabrowski** [comment]
It looks good. - the only thing that comes to my mind it the format of names of files for migration.
Let's think how would migration number 1000 look like... would it be V1000__xxx.sql ? And does this mechanism would apply it after V1__xxx.sql or V2__xxx.sql (I'm not sure, just something to think of and/or verify)?
would be perfect to have format like: 1_xxx.sql ... 1000_xxx.sql but might be we would need 00001_xxx.sql if prefix is interpreted as string rather then integer - please check it or find in documentation

**Comment by DominikSerwatka** [comment]
I checked and the migration with the names: V1__name.sql, V1.1__name.sql, V10__name.sql works correctly. The migrations were performed in the given order. The problem is with the file name for e.g. V001__name.sql

**Comment by jdabrowski** [comment]
sounds good then

**Review by jdabrowski — APPROVED** [review]

**Comment by ZbigniewStasienko** [comment]
I found some minor mistakes and fixed them

**Review by ZbigniewStasienko — APPROVED** [review]

**Pull request merged**
